### PR TITLE
introduce useDebounce

### PR DESCRIPTION
**Pull request by adrienpoly**
Introducing a new mixin for debouncing controllers functions. it follows a similar pattern as [useMemo](https://github.com/stimulus-use/stimulus-use/blob/master/docs/use-memo.md) with a static array "debounces" of function names to debounce

```js
import { ApplicationController, useDebounce } from 'stimulus-use'

export default class extends ApplicationController {
  static debounces = ['add']

  connect() {
    useDebounce(this, {delay: 100})
  }

  add() { 
  // this function is debounced
 }
}
```

### CODE REVIEW

**Comment by adrienpoly** [comment]
👋  @julianrubisch @marcoroth WDYT?

**Comment by julianrubisch** [comment]
good idea! we should look if there's some overlap with https://github.com/hopsoft/debounced

**Comment by julianrubisch** [comment]
oh it's already a PR, I thought it's a feature request... I'll take a look then

**Comment by julianrubisch** [comment]
looks all good to me!

**Comment by marcoroth** [comment]
Looks good to me as well! The only thing is asked myself: Should you be able to specify different delays for the different controller functions? 
But I think it's fine that you can just set it globally - also because I can't think of nice and intuitive syntax for that.

**Comment by julianrubisch** [comment]
we could go ahead and create `useThrottle` as well 😎

**Comment by adrienpoly** [comment]
That was my plan but wanted to play a bit first with the Debounce api

**Comment by adrienpoly** [comment]
@all-contributors add @julianrubisch to review

**Comment by adrienpoly** [comment]
@all-contributors add @marcoroth to review

**Pull request merged**
