### PR TITLE
`useTargetMutation`: Add deprecation mention for `[target]TargetAdded` and `[target]TargetRemoved`

### PR DESCRIPTION
**Pull request by ker0x**
This PR adds a depreciation mention for `[target]TargetAdded` and `[target]TargetRemoved` as their behavior appears to be identical to `[target]TargetConnected` and `[target]TargetDisconnected`.

Feel free to close if it's not 😉 !

### CODE REVIEW

**Comment by marcoroth** [comment]
Hey @ker0x, thanks for this, good catch!

Would you mind adding deprecation logs to the actual code as well?

https://github.com/stimulus-use/stimulus-use/blob/029624d7f1423e67ffa63ca1209a9c2afeda2b3e/src/use-target-mutation/use-target-mutation.ts

**Comment by ker0x** [comment]
> Would you mind adding deprecation logs to the actual code as well?

@marcoroth Done 😉 !

**Comment by marcoroth** [comment]
Awesome thanks! I have one more thing and then I think we can merge this.

Can we add another deprecation warning to the `useTargetMutation` method itself so you can already see it as soon as the `useTargetMutation` is called in the controller?

https://github.com/stimulus-use/stimulus-use/blob/efa70d81b89ba44e287ce36fa66c0eeb8850414a/src/use-target-mutation/use-target-mutation.ts#L212

**Comment by ker0x** [comment]
@marcoroth I've added it, but I'm not sure about it, because it will throw a warning even if you use the [`target]TargetChanged` function, right?

**Comment by marcoroth** [comment]
Oh, you are right. This almost makes me want to implement the changed target callback in upstream Stimulus.

**Comment by ker0x** [comment]
@marcoroth That would be great! There was a previous discussions and attempt to introduce it in Stimulus: hotwired/stimulus#445 and hotwired/stimulus#460

Regardint the PR, should I remove the warning on `useTargetMutation` ?

**Review by marcoroth — APPROVED** [review]
Thank you @ker0x! 🙏🏼

**Comment by marcoroth** [comment]
@all-contributors add @ker0x for code

**Comment by ker0x** [comment]
@marcoroth thank you 🙏 !

**Comment by brendon** [comment]
> @marcoroth I've added it, but I'm not sure about it, because it will throw a warning even if you use the [`target]TargetChanged` function, right?

I don't think this was ever removed again per: https://github.com/stimulus-use/stimulus-use/pull/471#issuecomment-1886706854

I'm getting the deprecation warning in the console regardless of whether I fix the problem or not.

**Comment by brendon** [comment]
> > @marcoroth I've added it, but I'm not sure about it, because it will throw a warning even if you use the [`target]TargetChanged` function, right?
> 
> I don't think this was ever removed again per: [#471 (comment)](https://github.com/stimulus-use/stimulus-use/pull/471#issuecomment-1886706854)
> 
> I'm getting the deprecation warning in the console regardless of whether I fix the problem or not.

Oh, disregard this. I misread it as a method name change deprecation rather than indicating that the functionality now exists in stimulus itself.

**Pull request merged**
